### ISSUE TITLE
stream nil in #hasNextAfterPoppingStreamsAtEnd

### ISSUE THREAD

**Issue by badetitou** [svenvc/XML-Support-Pharo#1]
Hello,

I'm trying to use this version of XMLDOMParser and I have a problem with a nil exception.
When I parse my file at the end I got "MessageNotUnderstood: receiver of ""atEnd"" is nil"

This happens at the end of the parsing, and commenting the line "self popCurrentStream." in the XMLNestedStreamReader>>#hasNextAfterPoppingStreamsAtEnd method fix the problem (but I suppose it creates something else?)

You can find the file I try to parse attached.
I parse it with the following line
```Smalltalk
xmlModel := (XMLDOMParser on: fileRef readStream)
	isValidating: false;
	parseDocument.
```

[GroupsDialog.ui.xml.txt](https://github.com/svenvc/XML-Support-Pharo/files/3683159/GroupsDialog.ui.xml.txt)

**Comment by svenvc** [comment]
Hi Benoît,

This repo is just a (static, one-version) copy of the original, not at all a way to support this code base.
I think you can better ask this question on the general mailing lists.

Sven

**Comment by seandenigris** [comment]
@svenvc It might be good to put that disclaimer in the README and maybe disable the issue tracker (in settings)...

**Comment by svenvc** [comment]
https://github.com/svenvc/XML-Support-Pharo/commit/21a22c9ee49788e6b4a2d80c5aabdefe2a0470ca
